creation_rules:
  # Secrets shared across all hosts
  - path_regex: nix/secrets/common\.yaml$
    key_groups:
      - age:
          - age160hzd3cahej40u6226t6c24hurcg8skg8l3l058jz4gvj24x23jshem5zg # thasso
          - age1teffze36axkjcz2pzcgzs2hawufxj77mmqvn3h3g9hskfyrmhqqqzv6cn8 # macbox
          - age1gtfh442v4e9ju4gczxjmgdg9n76fngaqr8cxep4lzrxlqwaay3zqv2994s # immobox
          - age1xae0pw26hmspa8h529zyhpg0c5pppef6327uemfc7djfxmtvqu8sgscz5g # limabox
          - age1hkdekhv37pgnrj9vptg35y84mpaupqgawprx4y6q2psaz62y8flqp6hu85 # devbox

  # Immobox-only secrets (Hetzner tokens, server-specific)
  - path_regex: nix/secrets/immobox\.yaml$
    key_groups:
      - age:
          - age160hzd3cahej40u6226t6c24hurcg8skg8l3l058jz4gvj24x23jshem5zg # thasso
          - age1hlk9ezjjh7kntejjfwad6vmuth6hz9fr8wuhp0k5arc65l74m3ys2az0lh # immobox

  # macbox-only secrets
  - path_regex: nix/secrets/macbox\.yaml$
    key_groups:
      - age:
          - age160hzd3cahej40u6226t6c24hurcg8skg8l3l058jz4gvj24x23jshem5zg # thasso
          - age1teffze36axkjcz2pzcgzs2hawufxj77mmqvn3h3g9hskfyrmhqqqzv6cn8 # macbox
