set nocompatible
execute pathogen#infect()
syntax on
filetype plugin indent on

" load .vimrc automatically on changes
if has("autocmd")
  autocmd! bufwritepost .vimrc source %
endif

" hidden mode
set hidden

" avoid hitting escape
imap jj <esc>

" renap leader to ,
let mapleader = ","

" navigation options
"
" bind Ctrl+<movement> keys to move around the windows, instead of using Ctrl+w + <movement>
" Every unnecessary keystroke that can be saved is good for your health :)
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h
" navigate between buffers
map <Leader>n :bn<CR>
map <Leader>m :bp<CR>

" Spell checker
set spelllang=en_US
map <Leader>s :set spell!<CR>

" exclude files from listings
set wildignore+=*.pyc,*.o,*.obj,.git
" Line numbers and line wrapping
set number
set tw=0
set wrap
set linebreak
map <leader>p gqip

" color column at 80
set colorcolumn=80
highlight ColorColumn ctermbg=235

" color scheme
if has('gui_running')
	set background=dark
	colorscheme solarized
	set guioptions-=T " disable toolbar
	set guifont=Source\ Code\ Pro\ for\ Powerline:h12
endif

" history and undo length
set history=700
set undolevels=700

" disable backup and swap files
set nobackup
set nowritebackup
set noswapfile

" set default tab sizes
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround

" enable exapnd tabs based on file type 
if has("autocmd")
  autocmd Filetype python setlocal expandtab
endif

" enable powerbar
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
set laststatus=2
set noshowmode

" configure search
set hlsearch " hightlight search
" turn off search highlighting with leader h
map <leader>h :nohlsearch<CR> 
set incsearch " incremental search
set ignorecase
set smartcase


" open lusty file explorer
map <leader>f :LustyFilesystemExplorer<CR>
